version: '3.8'
services:
  web:
    image: nginx
    ports:
      - '9080:80'
    volumes:
      - '/srv/dev-disk-by-id-md-name-Storage-firstRAID1/Configs/home-scooling/static:/var/www/static'
      - '/srv/dev-disk-by-id-md-name-Storage-firstRAID1/Configs/home-scooling/web.conf:/etc/nginx/conf.d/default.conf'
  app:
    image: artemshestakov/home-study:0.1.0
    environment:
      SECRET_KEY: 'django-insecure-lq!!p4ry5y3n-rc2enbdni*irz^*h9(+x5im5467u4n!#^(h=s'
    command:
      - 'gunicorn' 
      - '-c'
      - 'prod.py'
    volumes:
      - '/srv/dev-disk-by-id-md-name-Storage-firstRAID1/Configs/home-scooling/db:/app/db'