# Generated by Django 3.2.9 on 2021-12-02 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True, verbose_name='Study day'),
        ),
    ]
