# Generated by Django 3.2.9 on 2021-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_alter_lesson_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Subject title'),
        ),
    ]
